### ISSUE TITLE
repo_deb.c should handle control file without "./" prefix

### ISSUE THREAD

**Issue by lpapp** [openSUSE/sat-solver#4]
This needs to be patched: https://github.com/openSUSE/sat-solver/blob/master/ext/repo_deb.c#L574

Because:
deb(5) says: "The  second  required  member  is  named  control.tar.gz.   It is a gzipped tar archive containing the package control information, as a series of plain files, of which the file control is mandatory and contains the core control information. The control tarball may optionally contain an entry for `.', the current directory."

A good example for causing breakage is Harmattan.

The system-services package does not contain this "./" entry, which is not a mistake! Thank you in advance!

**Comment by mlschroe** [comment]
Thanks, I'll fix it in the "libsolv" repo. "libsolv" is the new name of "sat-solver".

**Comment by lpapp** [comment]
Thank you for the fast reply.

The fix is trivial, probably a simple "if (!strcmp((char *)bp, "./control") || !strcmp((char *)bp,
"control"))" change with modifying the relevant error print.

When can it be available in usage for OBS for instance ?

**Comment by mlschroe** [comment]
for now we'll just patch it in the BSSolv package in openSUSE:Tools

**Comment by mlschroe** [comment]
committed.
